library(shinytest2)

test_that("{shinytest2} recording: attainment-age-19", {
  app <- AppDriver$new(name = "attainment-age-19", height = 976, width = 1305)
  app$expect_values()
  app$set_inputs(tabsetpanels_fsm = "Local authority & Special Educational Need")
  app$expect_values()
  app$set_inputs(select3 = "Bedford")
  app$expect_values()
  app$set_inputs(select_cat2 = "Level 3")
  app$expect_values()
  app$set_inputs(select3 = "Birmingham")
  app$expect_values()
  app$set_inputs(tabsetpanels_fsm = "Local authority & Free School Meal Status")
  app$expect_values()
  app$set_inputs(select2 = "Birmingham")
  app$expect_values()
  app$set_inputs(navlistPanel = "Information")
  app$expect_values()
  app$set_inputs(navlistPanel = "Accessibility")
  app$expect_values()
  app$set_inputs(navlistPanel = "Support and feedback")
  app$expect_values()
  app$set_inputs(navlistPanel = "LA & FSM")
  app$expect_values()
})
